### ISSUE TITLE
How to set the sidebar width?

### ISSUE THREAD

**Issue by jackcaspers** [maelstrom-cms/toolkit#4] opened 2020-02-05 17:04 UTC
I'm using a custom sidebar with some items that have names that are longer than what is displayed in the sidebar. Currently it seems that the sidebar is set at 210px but I'm not sure how to change that value. I was wondering how to set the width of the sidebar so more of the name will get displayed? 
I did see it is getting set here `this.width = ParseProps(props, 'width', 210)` in `Sidebar.js`

**Comment by OwenMelbz** [comment] 2020-02-05 17:18
Hi,

If you publish the `sidebar.blade.php` which is located: https://github.com/maelstrom-cms/toolkit/blob/master/src/views/partials/sidebar.blade.php

Then you can pass in custom properties to it, e.g. your custom one might be like....

```php
// resources/views/vendor/maelstrom/partials/sidebar.blade.php

@include('maelstrom::components.sidebar', [
    'items' => $maelstrom_sidebar ?? [],
    'width' => 500,
])
```

Give that a whirl and see if it helps.

I'm going to close this ticket as it's not a bug (yet) but will continue to monitor it.

Thanks

**Closed as completed by OwenMelbz** 2020-02-05 17:18 UTC
Labels: question

**Comment by jackcaspers** [comment] 2020-02-05 20:58
Thank you!
